---

- name: Configuring
  template: >
    src={{ vsftpd_config_template if vsftpd_config_template else 'etc-vsftpd.conf.j2' }}
    dest=/etc/vsftpd.conf
    owner=root
    group=root
    mode=0644
  notify: restart vsftpd
  tags:
    - networking
    - vsftpd
    - config

- name: Adding nologin shell
  lineinfile: >
    state=present
    dest=/etc/shells
    line="/usr/sbin/nologin"
    regexp="^/usr/sbin/nologin"
    insertafter=EOF
  tags:
    - networking
    - vsftpd
    - config
